### ISSUE TITLE
桃子申请加友链

### ISSUE THREAD

**Issue by peachrl** [myanbin/talk#13]
孺子牛：

您好，我想和你交换友情链接。我的个人网站有关信息如下：

```yaml
name: peachRL的小站
url: https://wanyijizi.com/
avatar: https://image.wanyijizi.com/00000000_封面/avatar.jpg
desc: 万亿及秭
```
